- name: "Provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }} res_grp_type={{ res_item.2 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name'] }}"]
    - ["{{ res_grp['resource_group_type'] }}"]
  loop_control:
    loop_var: res_item
