---
- name: "Get topology output data from RunDB"
  rundb:
    conn_str: "{{ rundb_conn }}"
    operation: get
    table: "{{ target }}"
    key: "outputs"
    run_id: "{{ orig_run_id }}"
  register: topo_output

- name: Filter list for resources
  set_fact:
    topo_output_resources: "{{ topo_output['output'][0]['resources'] }}"

- name: "Teardown resource"
  include: teardown_{{ topo_output_res['resource_type'] }}.yml output_res={{ topo_output_res }}
  with_items: "{{ topo_output_resources }}"
  loop_control:
    loop_var: topo_output_res
