---
- name: "Unset the authvar from previous run"
  set_fact:
    auth_var: ""

- name: "set default_cred_profile when res_grp[credentials] is undefined"
  set_fact:
    cred_profile: 'default'
  when: res_grp['credentials'] is not defined

- name: "set default_cred_filename when res_grp[credentials] is undefined"
  set_fact:
    cred_filename: 'openshift.yaml'
  when: res_grp['credentials'] is not defined

  # sets cred profile as 'default' if key profile is not mentioned in
  # credentials section of topology
- name: "set default_cred_filename when res_grp[credentials] is undefined"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] | default('default') }}"
  when: res_grp['credentials'] is defined

- name: "set default_cred_filename when res_grp[credentials] is defined"
  set_fact:
    cred_filename: "{{ res_grp['credentials']['filename'] }}"
  when: res_grp['credentials'] is defined and res_grp['credentials']['filename'] is defined

- name: debug to checkout workspace env var
  debug:
    msg: "{{ lookup('env','workspace') }}"

- name: debug to checkout workspace extra var
  debug:
    msg: "{{ workspace }}"

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ cred_filename }}"
    cred_type: "openshift"
    cred_path: "{{ creds_path | default(default_credentials_path) }}"
    driver: "file"
  register: auth_var_out
  ignore_errors: true
  no_log: "{{ not debug_mode }}"
  when: res_grp['credentials'] is defined and res_grp['credentials']['filename'] is defined

- name: "Search creds from workspace when not found in default_credentials_path"
  auth_driver:
    filename: "{{ cred_filename }}"
    cred_type: "openshift"
    cred_path: "{{ creds_path | default(workspace) }}"
    driver: "file"
  register: auth_var_out
  ignore_errors: true
  no_log: "{{ not debug_mode }}"
  when: res_grp['credentials'] is defined and res_grp['credentials']['filename'] is defined and auth_var_out['failed']

- name: "set auth_var"
  set_fact:
    auth_var: "{{ auth_var_out['output'][cred_profile] }}"
  ignore_errors: true
  no_log: "{{ not debug_mode }}"
  when: auth_var_out['output'] is defined and res_grp['credentials'] is defined and res_grp['credentials']['filename'] is defined

- name: "set auth_var when filename is not defined"
  set_fact:
    auth_var: "{{ res_grp['credentials'] }}"
  when: res_grp['credentials'] is defined and res_grp['credentials']['filename'] is not defined
  ignore_errors: true

- name: "Initiating Provision/Teardown of openshift resource group"
  include: provision_res_defs.yml res_def={{ res_item }}
  with_items:
    - "{{ res_grp['resource_definitions'] }}"
  loop_control:
    loop_var: res_item
