---
- name: "declaring output vars"
  set_fact:
    topology_outputs_aws_ec2: []
    topology_outputs_aws_s3: []
    topology_outputs_aws_ec2_key: []
    topology_outputs_aws_cfn: []
    topology_outputs_aws_net: []

- name: "Initiating Provisioning of aws resource group"
  include_tasks: provision_resource_group.yml
  vars:
    res_grp: "{{ item }}"
  with_items:
    - "{{ resources }}"
  when: state == "present"

- name: "Initiating Teardown of aws resource group"
  include_tasks: teardown_resource_group.yml
  vars:
    res_grp: "{{ item }}"
  with_items:
    - "{{ resources }}"
  when: state == "absent"
