---
- name: "declaring output vars"
  set_fact:
    topology_outputs_aws_ec2: []
    topology_outputs_aws_s3: []
    topology_outputs_aws_ec2_key: []
    topology_outputs_aws_cfn: []

- name: "Initiating  Provisioning of resources aws resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ aws_res_grps }}"
  when: state == "present"
  check_mode: "{{ _check_mode }}"

- name: "Initiating  teardown of resources aws resource group"
  include: teardown_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ aws_res_grps }}"
  when: state == "absent"
