- name: "Provisioning AWS EC2 KEY "
  ec2_key:
    aws_access_key: "{{ auth_var['aws_access_key_id'] | default(omit) }}"
    aws_secret_key: "{{  auth_var['aws_secret_access_key'] | default(omit) }}"
    region: "{{ res_def['region'] }}"
    name:  "{{ res_def['res_name'] | default(res_def['name']) }}"
    state: "{{ state }}"
    wait: "yes"
  register: res_def_output
  no_log: "{{ not debug_mode }}"

- name: "Generate keyfile "
  copy: 
    content: "{{ res_def_output['key']['private_key'] }}"
    dest: "/{{ keystore_path | default('tmp') }}/{{ res_def['res_name'] | default(res_def['name']) }}.pem"
  when: state=="present" and res_def_output['changed']==true

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_aws_ec2_key: "{{ topology_outputs_aws_ec2_key + [res_def_output] }}"
  when: res_def_output['changed'] == true

- name: "Add type to resource"
  set_fact:
    topology_outputs_aws_ec2_key: "{{ topology_outputs_aws_ec2_key | add_res_type('aws_ec2_key_res') }}"
