---
- name: "Unset the authvar from previous run"
  set_fact:
    auth_var: !!null
  no_log: "{{ not debug_mode }}"

- name: "Set cred profile"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] | default('default') }}"
  when: res_grp['credentials'] is defined

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ res_grp['credentials']['filename'] }}"
    cred_type: "aws"
    cred_path: "{{ creds_path | default(default_credentials_path) }}"
    driver: "file"
    vault_enc: "{{ vault_encryption }}"
    vault_pass: "{{ vault_pass }}"
  register: auth_variable
  ignore_errors: true
  when: res_grp['credentials'] is defined
  no_log: "{{ not debug_mode }}"

- name: "Set auth_var"
  set_fact:
    auth_var: "{{ auth_variable['output'][cred_profile] | default('') }}"
  when: cred_profile is defined and auth_variable['changed']
  no_log: "{{ not debug_mode }}"

- name: "provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name']}}"]
  loop_control:
    loop_var: res_item
