---
- name: "Set cfn parameters for template"
  set_fact:
    cfn_grp_vars : "{{ res_grp_vars | selectattr('resource_group_name', 'match', '^' + res_grp_name + '$') | first }}"

- name: "Set cfn parameters for template"
  set_fact:
    cfn_params : "{{ cfn_grp_vars['cfn_params'] }}"

- name: "Provision cloud formation stack"
  cloudformation:
    aws_access_key: "{{ auth_var['aws_access_key_id'] | default(omit) }}"
    aws_secret_key: "{{  auth_var['aws_secret_access_key'] | default(omit) }}"
    stack_name:  "{{ res_def['res_name'] | default(res_def['name']) }}"
    state: "{{ state }}"
    region:  "{{ res_def['region'] }}"
    disable_rollback:  "{{ res_def['disable_roleback']| default(omit) }}"
    template: "{{ res_def['template_path'] }}"
    template_parameters: "{{ cfn_params }}"
    tags:
      Stack: "{{ res_def['res_name'] | default(res_def['name']) }}"
  register: res_def_output
  when: not async
  no_log: "{{ not debug_mode }}"

- name: "Provision cloud formation stack"
  cloudformation:
    aws_access_key: "{{ auth_var['aws_access_key_id'] | default(omit) }}"
    aws_secret_key: "{{  auth_var['aws_secret_access_key'] | default(omit) }}"
    stack_name:  "{{ res_def['res_name'] | default(res_def['name']) }}"
    state: "{{ state }}"
    region:  "{{ res_def['region'] }}"
    disable_rollback:  "{{ res_def['disable_roleback']| default(omit) }}"
    template: "{{ res_def['template_path'] }}"
    template_parameters: "{{ cfn_params }}"
    tags:
      Stack: "{{ res_def['res_name'] | default(res_def['name']) }}"
  register: res_def_output
  async: "{{ async_timeout }}"
  poll: 0
  when: async
  no_log: "{{ not debug_mode }}"

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_aws_cfn: "{{ topology_outputs_aws_cfn + [res_def_output] }}"
    
- name: "Add type to resource"
  set_fact:
    topology_outputs_aws_cfn: "{{ topology_outputs_aws_cfn | add_res_type('aws_cf_res') }}"
