sudo: false

# make ubuntu 16.04 the default version
dist: bionic

language: python

python:
  - "2.7"
  - "3.7"

cache: pip

install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install .
  - pip install .[tests]

script:
  - flake8 --exclude=\.eggs,tests,docs --ignore=E124,E303,W504 --max-line-length 80 .
  - $(which python) setup.py test
#  - $(which python) $(which nosetests) -s linchpin/tests/*
