---
- name: "Get the resource name"
  set_fact:
    dummy_name: "{{ res_def['name'] }}"

- name: "Assign dummy name using uhash value"
  set_fact:
    dummy_name: "{{ dummy_name + '-' + uhash }}"
  when: enable_uhash

- name: "Provision dummy resources by looping on count"
  dummy:
    state: present
    name: "{{ dummy_name }}"
    count: "{{ res_def['count'] | default(1) }}"
    domain: "{{ res_def['domain'] | default('') }}"
  register: outputitem

- name: "set tmp var"
  set_fact:
    tmp: ["{{ outputitem }}"]

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_dummy: "{{ topology_outputs_dummy + tmp }}"

- name: "Add type to resource"
  set_fact:
    topology_outputs_dummy: "{{ topology_outputs_dummy | add_res_type('dummy_res') }}"
