- name: "debug task"
  debug:
    msg: "{{ os_server_group }}"

- name: "waiting on each job id"
  async_status_custom:
    jid: "{{ item['ansible_job_id'] }}"
    module_name: "os_server"
  register: job_result
  until: job_result.finished
  retries: 30
  with_items: "{{ os_server_group['results']}}"

- name: "Append outputitem to topology_outputs"
  set_fact:
    async_outputs_os_server: "{{ async_outputs_os_server + [job_result] }}"
