---
- name: "define network"
  virt_net:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    command: define
    xml: "{{ lookup('template', 'libvirt_network.xml.j2') }}"
    uri: "{{ res_def['uri'] | default('qemu:///system') }}"
  register: res_def_output
  when: not async
  ignore_errors: yes

- name: "start network"
  virt_net:
    state: active
    uri: "{{ res_def['uri'] | default('qemu:///system') }}"
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
