---
#- name: "provision libvirt storage"
#  include: provision_libvirt_storage.yml
- name: "Get host from uri"
  set_fact:
    uri_hostname: "{{ res_def['uri'] | get_host_from_uri }}"

- name: set resource_type
  set_fact:
    resource_type: "{{ res_def['role'] }}"

- name: "provision libvirt network"
  include: provision_libvirt_network.yml
  when:
    - resource_type == "libvirt_network"
    - state == "present"

- name: "teardown libvirt network"
  include: teardown_libvirt_network.yml
  when:
    - resource_type == "libvirt_network"
    - state == "absent"
    - res_def['delete_on_destroy'] is defined
    - res_def['delete_on_destroy'] == True

- name: "Set the resource node name"
  set_fact:
    libvirt_resource_name: "{{ res_def['name'] }}"

- name: "Create name using uhash value"
  set_fact:
    libvirt_resource_name: "{{ libvirt_resource_name + '-' + uhash }}"
  when: enable_uhash

- name: "provision libvirt node"
  include: provision_libvirt_node.yml
  when:
    - resource_type == "libvirt_node"
    - state == "present"

- name: "teardown libvirt node"
  include: teardown_libvirt_node.yml
  when:
    - resource_type == "libvirt_node"
    - state == "absent"

