# These are arguments which you will need to override
# URL for the Jenkins master this slave should attach to
jenkins_url: http://example.com:8080/jenkins/

# These are variables which you may wish to override
# The Jenkins name for the slave
jslave_name: "{{ inventory_hostname }}"
# The label for this slave
jslave_label: ops-jslave
# Number of executor processes on the slave - modify based on system capacity and load
jswarm_execs: 10
# Directory where the swarm will live and execute
jswarm_home: /home/jenkins
# Whether the swarm should execute as the jenkins user. False means it will exec as root
run_swarm_as_jenkins: false
# The home directory for the user who will be executing the swarm process
jenkins_user_home: /root
# The name of the user who will be executing the swarm process
jenkins_user: root

# These are variables which you probably don't want to
# override, but which you are free to override if you
# feel the need to
jswarm_filename: swarm-client-{{ jswarm_version }}-jar-with-dependencies.jar
jswarm_download: http://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/swarm-client/{{ jswarm_version }}/{{ jswarm_filename }}

# These are variables that you really should not override
# unless you really know what you're doing
jslave_rpm_deps:
  - python-paramiko
  - git
  - gcc
  - krb5-workstation
  - wget
  - python-pip
  - python-unittest2
  - python-pep8
  - python-flake8
  - python-futures
  - python-devel
  - nss
