apiVersion: v1
kind: Template
labels:
  template: centos7-builder
metadata:
  annotations:
    description: centos7 container
    iconClass: centos7
    tags: instant-app
  name: centos7-builder
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
    labels:
    name: centos7
  spec: {}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: centos7
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: centos7:latest
    resources: {}
    source:
      contextDir: ${REPO_CONTEXTDIR}
      git:
        ref: ${REPO_REF}
        uri: ${REPO_URL}
      type: Git
    strategy:
      dockerStrategy:
        dockerfilePath: centos7/Dockerfile
        env:
          - name: CONTAINER_NAME
            value: centos7
      type: Docker
    triggers:
    - type: ConfigChange
parameters:
- description: Git repository with Dockerfile and slave entrypoint.
  displayName: Repository URL
  name: REPO_URL
  value: https://github.com/p3ck/linchpin.git
- description: The sub-directory inside the repository.
  displayName: Context Directory
  name: REPO_CONTEXTDIR
  value: config/Dockerfiles
- description: The git ref or tag to use for customization.
  displayName: Git Reference
  name: REPO_REF
  value: openshift-release1.5
