---
- name: "declaring output vars"
  set_fact:
    topology_outputs_azure_vm: []
    topology_outputs_azure_vn: []
    topology_outputs_azure_vn_subnet: []

- name: "Initiating Provisioning of Azure resource group"
  include: provision_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ resources }}"
  when: state == "present"
  check_mode: "{{ _check_mode }}"

- name: "Initiating Teardown of Azure resource group"
  include: teardown_resource_group.yml res_grp={{ item }}
  with_items:
    - "{{ resources }}"
  when: state == "absent"
