---
- name: "Set azure_res_type value"
  set_fact:
    aws_res_type: "{{ res_def['role'] }}"
  when: _async

- name: "Add resource type to async_types"
  set_fact:
    async_types: "{{ async_types + [azure_res_type] }}"
  when: _async

- name: "declaring async vars"
  set_fact:
    asyn ac_outputs_azure_vm: []
  when: _async

- name: "Get the resource name"
  set_fact:
    rsrc_name: "{{ res_def['res_name'] | default(res_def['vm_name']) }}"

- name: "Create name using uhash value"
  set_fact:
    aws_resource_name: "{{ rsrc_name + '-' + uhash + '-' }}"

- name: "provision resource type : {{ res_def['role'] }}"
  include: "provision_{{ res_def['role'] }}.yml"
