- name: "Teardown Azure VM"
  azure_rm_virtualmachine:
    client_id: "{{ auth_var['client_id'] | default(omit) }}"
    tenant: "{{ auth_var['tenant'] | default(omit) }}"
    secret: "{{ auth_var['secret'] | default(omit) }}"
    subscription_id: "{{ auth_var['subscription_id'] | default(omit) }}"
    resource_group: "{{ res_def['resource_group'] | default(omit) }}"
    remove_on_absent: "{{res_def['delete_all_attached']|default('all_autocreated')}}"
    name: "{{ res_def['vm_name'] | default(omit) }}"
    state: 'absent'

- name: Delete managed disk
  azure_rm_manageddisk:
    client_id: "{{ auth_var['client_id'] | default(omit) }}"
    tenant: "{{ auth_var['tenant'] | default(omit) }}"
    secret: "{{ auth_var['secret'] | default(omit) }}"
    subscription_id: "{{ auth_var['subscription_id'] | default(omit) }}"
    name: "{{ res_def['vm_name']+".vhd" | default(omit) }}"
    resource_group: "{{ res_def['resource_group'] | default(omit) }}"
    state: absent
  when: res_def['deepclean'] is defined and res_def['deepclean'] == true
  ignore_errors: true
