---
# This playbook will initiate provisioning for the openstack resources groups.
#- name: "DEBUG:: Openstack resource group list"
#  debug:
#    msg: "Currently Provisioning/Deprovisioning the resources under list os_res_grps {{ os_res_grps }}"

- name: "declaring output vars"
  set_fact:
    topology_outputs_os_server: []
    topology_outputs_os_object: []
    topology_outputs_os_volume: []
    topology_outputs_os_heat: []
    topology_outputs_os_keypair: []
    topology_outputs_os_sg: []
    topology_outputs_os_network: []
    topology_outputs_os_router: []
    topology_outputs_os_subnet: []

- name: "Initiating Provision of openstack resource group"
  include_tasks: provision_resource_group.yml
  vars:
    res_grp: "{{ item }}"
  with_items:
    - "{{ resources }}"
  register: resource_grps_output
  when: state == "present"

- name: "Initiating Teardown of openstack resource group"
  include_tasks: teardown_resource_group.yml
  vars:
    res_grp: "{{ item }}"
  with_items:
    - "{{ resources }}"
  when: state == "absent"
