---
- name: "provision/teardown security group with auth"
  os_security_group:
    auth: "{{ auth_var | default(omit) }}"
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    description: "{{ res_def['description'] | default('Created by LinchPin') }}"
    state: "{{ state }}"
    wait: "yes"
  when: auth_var is defined

- name: "provision/teardown security group no auth"
  os_security_group:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    description: "{{ res_def['description'] | default('Created by LinchPin') }}"
    state: "{{ state }}"
    wait: "yes"
  when: auth_var is not defined

- name: "provision/teardown security group"
  os_security_group_rule:
    auth: "{{ group.0 }}"
    security_group: "{{ group.1 }}"
    state: "{{ group.2 }}"
    protocol: "{{ group.3['proto']  }}"
    direction: "{{ group.3['rule_type'] | os_sg_rule_type }}"
    port_range_min: "{{ group.3['from_port'] }}"
    port_range_max: "{{ group.3['to_port'] }}"
    remote_ip_prefix: "{{ group.3['cidr_ip']  }}"
    wait: "yes"
  with_nested:
    - ["{{ auth_var | default(omit) }}"]
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ state }}"]
    - "{{ res_def['rules'] }}"
  loop_control:
    loop_var: group
  register: res_def_output
  when: state == "present" and auth_var is defined

- name: "provision/teardown security group"
  os_security_group_rule:
    security_group: "{{ group.0 }}"
    state: "{{ group.1 }}"
    protocol: "{{ group.2['proto']  }}"
    direction: "{{ group.2['rule_type'] | os_sg_rule_type }}"
    port_range_min: "{{ group.2['from_port'] }}"
    port_range_max: "{{ group.2['to_port'] }}"
    remote_ip_prefix: "{{ group.2['cidr_ip']  }}"
    wait: "yes"
  with_nested:
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ state }}"]
    - "{{ res_def['rules'] }}"
  loop_control:
    loop_var: group
  register: res_def_output
  when: state == "present" and auth_var is not defined

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_sg: "{{ topology_outputs_os_sg + [res_def_output] }}"
  when: state == "present"
