---
- name: "Unset the authvar from previous run"
  set_fact:
    auth_var: ""

- name: "set default_cred_profile when res_grp[credentials] is undefined"
  set_fact:
    cred_profile: 'default'
  when: res_grp['credentials'] is not defined

- name: "set default_cred_profile when res_grp[credentials] is undefined"
  set_fact:
    cred_filename: 'clouds.yaml'
  when: res_grp['credentials'] is not defined

- name: "set cred_profile when res_grp[credentials] is defined"
  set_fact:
    cred_profile: "{{ res_grp['credentials']['profile'] }}"
  when: res_grp['credentials'] is defined

- name: "set default_cred_filename when res_grp[credentials] is defined"
  set_fact:
    cred_filename: "{{ res_grp['credentials']['filename'] }}"
  when: res_grp['credentials'] is defined

- name: "Get creds from auth driver"
  auth_driver:
    filename: "{{ cred_filename }}"
    cred_type: "openstack"
    cred_path: "{{ creds_path | default(default_credentials_path) }}"
    driver: "file"
    vault_enc: "{{ vault_encryption }}"
    vault_pass: "{{ vault_pass }}"
  register: auth_var_out
  ignore_errors: true
  no_log: "{{ not debug_mode }}"
  when: res_grp['credentials'] is defined

- name: "set auth_var"
  set_fact:
    auth_var: "{{ auth_var_out['output']['clouds'][cred_profile]['auth'] }}"
  ignore_errors: true
  when: auth_var_out['output'] is defined
  no_log: "{{ not debug_mode }}"

- name: "provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] | default(res_grp['resource_definitions']) }}"
    - ["{{ res_grp['resource_group_name'] }}"]
  loop_control:
    loop_var: res_item
