---
- name: "provision/deprovision the os volume resource type"
  os_volume:
    auth: "{{ auth_var | default(omit) }}"
    state: "{{ state }}"
    size: "{{ res_def['size'] }}"
    display_name: "{{ res_def['res_name'] | default(res_def['name']) }}"
  when: res_def['count'] is not defined and auth_var is defined

- name: "provision/deprovision the os volume resource type"
  os_volume:
    state: "{{ state }}"
    size: "{{ res_def['size'] }}"
    display_name: "{{ res_def['res_name'] | default(res_def['name']) }}"
  when: res_def['count'] is not defined and auth_var is not defined

- name: "Register resource count"
  shell: python -c "print [x for x in range( 0, {{ res_def['count'] }} )]"
  register: res_count
  when: res_def['count'] is defined

- name: "provision/deprovision cinder volumes when count specified"
  os_volume:
    auth: "{{ vol.0 }}"
    state: "{{ vol.3 }}"
    size: "{{ vol.2 }}"
    display_name: "{{ vol.1 }}_{{ vol.4 }}"
  with_nested:
    - ["{{ auth_var | default(omit) }}"]
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  register: res_def_output
  when: res_def['count'] is defined and not async and auth_var is defined

- name: "provision/deprovision cinder volumes when count specified"
  os_volume:
    state: "{{ vol.2 }}"
    size: "{{ vol.1 }}"
    display_name: "{{ vol.0 }}_{{ vol.3 }}"
  with_nested:
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  register: res_def_output
  when: res_def['count'] is defined and not async and auth_var is not defined

- name: "Append outputitem to topology_outputs"
  set_fact:
    topology_outputs_os_volume: "{{ topology_outputs_os_volume + res_def_output.results }}"
  when: not async


- name: "Async:: provision/deprovision cinder volumes when count specified"
  os_volume:
    auth: "{{ vol.0 }}"
    state: "{{ vol.3 }}"
    size: "{{ vol.2 }}"
    display_name: "{{ vol.1 }}_{{ vol.4 }}"
  with_nested:
    - ["{{ auth_var | default(omit) }}"]
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: res_def['count'] is defined and async and auth_var is defined

- name: "Async:: save the job id"
  set_fact:
    topology_outputs_os_volume: "{{ topology_outputs_os_volume + [ res_def_output ] }}"
  when: async and auth_var is defined

- name: "Async:: provision/deprovision cinder volumes when count specified"
  os_volume:
    state: "{{ vol.2 }}"
    size: "{{ vol.1 }}"
    display_name: "{{ vol.0 }}_{{ vol.3 }}"
  with_nested:
    - ["{{ res_def['res_name'] | default(res_def['name']) }}"]
    - ["{{ res_def['size'] }}"]
    - ["{{ state }}"]
    - "{{ res_count.stdout }}"
  loop_control:
    loop_var: vol
  async: "{{ async_timeout }}"
  poll: 0
  register: res_def_output
  when: res_def['count'] is defined and async and auth_var is not defined

- name: "Async:: save the job id"
  set_fact:
    topology_outputs_os_volume: "{{ topology_outputs_os_volume + [ res_def_output ] }}"
  when: async and auth_var is not defined
