---
- name: "assign async value"
  set_fact:
    async: "{{ _async }}"
  when: async is not defined

- name: "declare async_types array"
  set_fact:
    async_types: []
  when: async

- name: "output vars"
  set_fact:
    topology_outputs: {}

