- name: "Provision/Teardown resource by looping on count"
  gce2:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    num_instances: "{{ res_def['count'] | default(omit)}}"
    zone: "{{ res_def['region'] }}"
    machine_type: "{{ res_def['flavor']  }}"
    image: "{{ res_def['image']  }}"
    state: "{{ state }}"
    service_account_email: "{{ auth_var['output']['client_email'] }}"
    credentials_file: "{{ auth_var['path'] }}/{{ auth_var['params']['filename'] }}.json"
    project_id: "{{ auth_var['output']['project_id'] }}"
  register: res_def_output
  when: not async

- name: "Appending outputitem to topology_outputs"
  set_fact:
    topology_outputs_gce: "{{ topology_outputs_gce + [res_def_output] }}"
  when: not async

- name: "Async:: Provision/Teardown resource by looping on count"
  gce2:
    name: "{{ res_def['res_name'] | default(res_def['name']) }}"
    num_instances: "{{ res_def['count'] | default(omit)}}"
    zone: "{{ res_def['region'] }}"
    machine_type: "{{ res_def['flavor']  }}"
    image: "{{ res_def['image']  }}"
    state: "{{ state }}"
    service_account_email: "{{ auth_var['output']['client_email'] }}"
    credentials_file: "{{ auth_var['path'] }}/{{ auth_var['params']['filename'] }}.json"
    project_id: "{{ auth_var['output']['project_id'] }}"
  register: res_def_output
  when: async
  async: "{{ async_timeout }}"
  poll: 0

- name: "Appending outputitem to topology_outputs"
  set_fact:
    topology_outputs_gce: "{{ topology_outputs_gce + [ res_def_output ] }}"
  when: async
