- name: "Provision/Teardown gcloud_gce_eip"
  gce_eip:
    name: "{{ gce_resource_name }}"
    state: "{{ state }}"
    region: "{{ res_def['region'] }}"
    service_account_email: "{{ auth_var['output']['client_email'] }}"
    credentials_file: "{{ auth_var['path'] }}/{{ auth_var['params']['filename'] }}"
    project_id: "{{ auth_var['output']['project_id'] }}"
  register: res_def_output
  no_log: "{{ not debug_mode }}"

- name: "Appending outputitem to topology_outputs"
  set_fact:
    topology_outputs_gcloud_gce: "{{ topology_outputs_gcloud_gce + [res_def_output] }}"
  when: not async

- name: "Add type to resource"
  set_fact:
    topology_outputs_gcloud_gce: "{{ topology_outputs_gcloud_gce | add_res_type('gcloud_gce_eip') }}"
