- name: "Provision/Teardown resource by looping on count"
  gce:
    name: "{{ gce_resource_name }}"
    num_instances: "{{ res_def['count'] | default(omit)}}"
    zone: "{{ res_def['region'] }}"
    machine_type: "{{ res_def['flavor']  }}"
    image: "{{ res_def['image']  }}"
    state: "{{ state }}"
    service_account_email: "{{ auth_var['output']['client_email'] }}"
    credentials_file: "{{ auth_var['path'] }}/{{ auth_var['params']['filename'] }}"
    project_id: "{{ auth_var['output']['project_id'] }}"
    tags: "{{ res_def['tags'] | default(omit) }}"
  register: res_def_output
  when: not async
  #  no_log: "{{ not debug_mode }}"

- name: "Appending outputitem to topology_outputs"
  set_fact:
    topology_outputs_gcloud_gce: "{{ topology_outputs_gcloud_gce + [res_def_output] }}"
  when: not async

- name: "Async:: Provision/Teardown resource by looping on count"
  gce:
    name: "{{ gce_resource_name }}"
    num_instances: "{{ res_def['count'] | default(omit)}}"
    zone: "{{ res_def['region'] }}"
    machine_type: "{{ res_def['flavor']  }}"
    image: "{{ res_def['image']  }}"
    state: "{{ state }}"
    service_account_email: "{{ auth_var['output']['client_email'] }}"
    credentials_file: "{{ auth_var['path'] }}/{{ auth_var['params']['filename'] }}"
    project_id: "{{ auth_var['output']['project_id'] }}"
    tags: "{{ res_def['tags'] | default(omit) }}"
  register: res_def_output
  when: async
  async: "{{ async_timeout }}"
  poll: 0
  no_log: "{{ not debug_mode }}"

- name: "Appending outputitem to topology_outputs"
  set_fact:
    async_outputs_gcloud_gce: "{{ async_outputs_gcloud_gce + [ res_def_output ] }}"
  when: async

- name: "Add type to resource"
  set_fact:
    topology_outputs_gcloud_gce: "{{ topology_outputs_gcloud_gce | add_res_type('gcloud_gce_res') }}"

- name: "Async:: Add type to resource"
  set_fact:
    async_outputs_gcloud_gce: "{{ async_outputs_gcloud_gce | add_res_type('gcloud_gce_res') }}"
  when: async
