---
- name: "Get topology output data"
  rundb:
    conn_str: "{{ rundb_conn }}"
    operation: get
    table: "{{ target }}"
    key: "outputs"
    run_id: "{{ orig_run_id }}"
  register: topo_output

- name: "set topo_output_resources fact"
  set_fact:
    topo_output_resources: "{{ topo_output.output[0]['resources'] }}"

- name: "debug res_grp"
  debug:
    var: res_grp

- name: "Set cred filename"
  set_fact:
    credentials: "{{ res_grp['credentials'] | default('') }}"
  when: res_grp['credentials'] is defined

- name: "debug topo_output"
  debug:
    var: topo_output_resources

- name: "Build duffy teardown list"
  set_fact:
    duffy_output_resources: "{{ topo_output_resources | get_provider_resources('duffy_res') }}"


- name: "Teardown resource definitions of current group"
  include: teardown_res_defs.yml ssid="{{ item['ssid'] }}"
  with_items: "{{ duffy_output_resources }}"
