---
- name: "Teardown Duffy Resources"
  duffy:
    ssid: "{{ ssid }}"
    state: 'absent'
    key_path: "{{ creds_path }}/{{ credentials }}"
  loop_control:
    loop_var: res_def_item
  register: output_item

- name: "Save the results"
  set_fact:
    topology_outputs_aws_ec2: "{{ topology_outputs_duffy + [output_item] }}"
