- name: "DEBUG:: provisioning resource group {{ res_grp }}"
  debug:
    msg: "The current Resource Group obj is {{ res_grp }} "

- name: "Including credentials of current resource {{ res_grp['resource_group_name'] }} "
  include_vars: "roles/aws/vars/{{ res_grp['assoc_creds'] }}.yml"
  no_log: true 

- name: "provisioning resource definitions of current group"
  include: provision_res_defs.yml res_def={{ res_item.0 }} res_grp_name={{ res_item.1 }}
  with_nested:
    - "{{ res_grp['res_defs'] }}"
    - ["{{ res_grp['resource_group_name']}}"]
  loop_control:
    loop_var: res_item
