---
- name: "Get topology output data from RunDB"
  rundb:
    conn_str: "{{ rundb_conn }}"
    operation: get
    table: "{{ target }}"
    key: "outputs"
    run_id: "{{ orig_run_id }}"
    db_schema: "{{ rundb_schema }}"
  register: topo_output

- name: Filter list for resources
  set_fact:
    topo_output_resources: "{{ topo_output.output | filter_list_by_attr('resources') }}"

- name: "set topo_output_resources fact"
  set_fact:
    topo_output_resources: "{{ topo_output_resources[0]['resources'] }}"

- name: "Deprovision resources"
  bkr_server:
    recipesets: "{{ topo_output_resources | fetch_beaker_job_ids }}"
    state: absent
    cancel_message: "cancelled provisioning on teardown request"
