galaxy_info:
  author: Samvaran Rallabandi
  description: openstack provisioning for LinchPin
  company: Red Hat, Inc.
  license: GPLv3
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
        - 8
    - name: Fedora
      versions:
        - 30
        - 31

  galaxy_tags:
    - oasis
    - linchpin
    - openstack
