name: "Lint testing: Testing container matrix [fedora31]"

on: [pull_request]

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['fedora:31']
    steps:
    - uses: actions/checkout@v2
    - run: cat /etc/os-release
    - name: running a shell script file
      run: |
        chmod +x ./.github/install_dependencies.sh
        ./.github/install_dependencies.sh
        pip3 install -e .[tests]
    - name: install flake8
      run: |
        pip install radon['flake8']
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        echo $PWD;
        ls;
        flake8 --exclude=\.eggs,tests,docs,config/Dockerfiles --ignore=E124,E303,W504 --max-line-length 80 .
        #flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics;
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    - name: "Execute linting for AWS role"
      run: |
        cd ./linchpin/provision/roles/aws
        molecule lint -s delegated
    - name: "Execute linting for Docker role"
      run: |
        cd ./linchpin/provision/roles/docker
    - name: "Execute linting for Duffy role"
      run: |
        cd ./linchpin/provision/roles/duffy
        molecule lint -s delegated
    - name: "Execute linting for Google Cloud role"
      run: |
        cd ./linchpin/provision/roles/gcloud
        molecule lint -s delegated
    - name: "Execute linting for Openshift role"
      run: |
        cd ./linchpin/provision/roles/openshift
    - name: "Execute linting for OpenStack role"
      run: |
        cd ./linchpin/provision/roles/openstack
        molecule lint -s delegated
    - name: "Execute linting for VMware role"
      run: |
        cd ./linchpin/provision/roles/vmware
        molecule lint -s delegated
    - name: "Execute linting for Ovirt role"
      run: |
        cd ./linchpin/provision/roles/ovirt
