name: "multicontainer Testing on container matrix"

on: [push, pull_request]

jobs:
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['centos:7', 'centos:8', 'fedora:30', 'fedora:31', 'fedora:32']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - run: cat /etc/os-release
    - name: running a shell script file
      run: |
        chmod +x ./.github/install_dependencies.sh
        ./.github/install_dependencies.sh
    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        pip3 install pytest
        pip3 install pytest-runner
        pip3 install .[tests]
        pip3 install zipp>=0.5
    - name: Run unit tests
      run: |
        coverage run --include "linchpin/*" setup.py test
    - name: Report on code coverage
      run: |
        coverage report
    - name: Run AWS mock tests
      run: |
        chmod +x ./.github/run_aws_mocktests.sh
        ./.github/run_aws_mocktests.sh
    - name: Run Openstack mock tests
      run: |
        chmod +x ./.github/run_openstack_mocktests.sh
        ./.github/run_openstack_mocktests.sh
    - name: Run beaker mock tests
      run: |
         chmod +x ./.github/run_beaker_mocktests.sh
         ./.github/run_beaker_mocktests.sh
    - name: Run gcloud mock tests
      run: |
        chmod +x ./.github/run_gcloud_mocktests.sh
        ./.github/run_gcloud_mocktests.sh
    - name: Run azure mock tests
      run: |
        chmod +x ./.github/run_azure_mocktests.sh
        ./.github/run_azure_mocktests.sh



